name: Deploy Vue Project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Use latest version of the action

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Use the updated action version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue-project  # Path to the folder containing index.html
